apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cluster-profile: profile1
  labels:
    app: my-operator
  name: my-operator
  namespace: my-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-operator
  template:
    metadata:
      labels:
        app: my-operator
    spec:
      containers:
      - args:
        - --logtostderr
        - start
        env:
        - name: RELEASE_VERSION
          value: 0.0.1-snapshot
        image: quay.io/openshift/my-operator:latest
        name: operator
        ports:
        - containerPort: 8443
          name: https
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
        - mountPath: /config
          name: config
      priorityClassName: system-cluster-critical
      serviceAccountName: operator
      volumes:
      - configMap:
          name: operator-config
        name: config
