apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-operator
  namespace: my-operator
  labels:
    app: my-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-operator
  template:
    metadata:
      labels:
        app: my-operator
    spec:
      serviceAccountName: operator
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      volumes:
      - name: config
        configMap:
          name: operator-config
      containers:
      - args:
        - --logtostderr
        - start
        image: quay.io/openshift/my-operator:latest
        name: operator
        ports:
        - containerPort: 8443
          name: https
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
        - mountPath: /config
          name: config
        env:
        - name: RELEASE_VERSION
          value: "0.0.1-snapshot"
