apiVersion: v1
kind: Service
metadata:
  name: my-operator
  namespace: my-operator
  labels:
    app: my-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  type: ClusterIP
  selector:
    app: my-operator
  ports:
  - name: https
    port: 8443
