apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: myoperatorresources.operator.openshift.io
spec:
  group: operator.openshift.io
  names:
    kind: MyOperatorResource
    plural: myoperatorresources
  scope: ""
  versions:
  - name: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
